runtime: php72

env_variables:
   APP_KEY: base64:vBoiaPDMY1+0KJQtIbnX/treqs4TjSGa6qnMmVgTuj4=
   APP_STORAGE: /tmp
   VIEW_COMPILED_PATH: /tmp
   CACHE_DRIVER: database
   SESSION_DRIVER: database
   DB_DATABASE: maxlearnpro
   DB_USERNAME: root
   DB_PASSWORD: maxprolearn@3216
   DB_SOCKET: "/cloudsql/fluted-vehicle-277421:asia-south1:maxprolearn-3322"