runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:XALX0ogwcEFiPw0lUO77SKhF2UDP1FAxFV/OA46wMSs=
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: maxlearnpro
  DB_USERNAME: maxlearnadmin
  DB_PASSWORD: maxlearnpro
  DB_SOCKET: "/cloudsql/weighty-sled-258508:asia-south1:maxprolearn-3322"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "weighty-sled-258508:asia-south1:maxprolearn-3322"